name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: lint
        run: yarn lint
      - name: format
        run: yarn prettier:check

  contract-test:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    needs: [setup, check]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Create files
        run: touch .env.local
      - name: Add secret values
        run: echo -e "PRIVATE_KEY=\"${{secrets.PRIVATE_KEY}}\"\nWALLET_ADDRESS=\"${{secrets.WALLET_ADDRESS}}\"\nALCHEMY_API_URL=\"${{secrets.ALCHEMY_API_URL}}\"" > .env.local
      - name: integration_test
        run: yarn test
